use std::collections::HashMap;
use std::io::Write;

use qc_model::policy_ir::{AdmissionRule, BypassRule, PolicyIR};

pub(super) fn compile_akamai(
    ir: &PolicyIR,
    score_map: Option<&HashMap<String, f64>>,
    output: &std::path::Path,
) -> anyhow::Result<()> {
    let mut children = Vec::new();

    // 1. Cache key normalization → cacheKeyQueryParams behavior
    let strip_params = extract_strip_params(&ir.cache_key_rules);
    if !strip_params.is_empty() {
        children.push(serde_json::json!({
            "name": "qc: cache key normalization",
            "criteria": [],
            "behaviors": [{
                "name": "cacheKeyQueryParams",
                "options": {
                    "behavior": "IGNORE",
                    "parameters": strip_params,
                    "exactMatch": false
                }
            }],
            "children": [],
            "criteriaMustSatisfy": "all"
        }));
    }

    // 2. Bypass rules → caching NO_STORE child rules
    compile_akamai_bypass(&ir.bypass_rule, &mut children);

    // 3. TTL class rules → caching MAX_AGE child rules
    for rule in &ir.ttl_class_rules {
        let ct_values = if rule.content_type_pattern.ends_with('/') {
            vec![format!("{}*", rule.content_type_pattern)]
        } else {
            vec![rule.content_type_pattern.clone()]
        };

        children.push(serde_json::json!({
            "name": format!("qc: TTL {} → {}s", rule.content_type_pattern, rule.ttl_seconds),
            "criteria": [{
                "name": "contentType",
                "options": {
                    "matchOperator": "IS_ONE_OF",
                    "matchWildcard": true,
                    "matchCaseSensitive": false,
                    "values": ct_values
                }
            }],
            "behaviors": [{
                "name": "caching",
                "options": {
                    "behavior": "MAX_AGE",
                    "mustRevalidate": false,
                    "ttl": seconds_to_akamai_ttl(rule.ttl_seconds)
                }
            }],
            "children": [],
            "criteriaMustSatisfy": "all"
        }));
    }

    // 4. Admission gate → EdgeWorker behavior
    let cache_key_config = if strip_params.is_empty() {
        None
    } else {
        Some(serde_json::json!({ "query_string_strip": strip_params }))
    };
    let edgeworker = match &ir.admission_rule {
        AdmissionRule::Always => None,
        AdmissionRule::ScoreThreshold { threshold } => Some(gen_akamai_edgeworker(
            *threshold,
            "score",
            score_map,
            cache_key_config.as_ref(),
        )),
        AdmissionRule::ScoreDensityThreshold { threshold } => Some(gen_akamai_edgeworker(
            *threshold,
            "density",
            score_map,
            cache_key_config.as_ref(),
        )),
    };

    if edgeworker.is_some() {
        children.push(serde_json::json!({
            "name": "qc: admission gate",
            "criteria": [{
                "name": "requestType",
                "options": {
                    "matchOperator": "IS",
                    "value": "CLIENT_REQ"
                }
            }],
            "behaviors": [{
                "name": "edgeWorker",
                "options": {
                    "enabled": true,
                    "edgeWorkerId": "{{QC_EDGEWORKER_ID}}"
                }
            }],
            "children": [],
            "criteriaMustSatisfy": "all"
        }));
    }

    // Assemble PAPI rule tree
    let rule_tree = serde_json::json!({
        "rules": {
            "name": "default",
            "comments": "Generated by quant-cache",
            "criteria": [],
            "behaviors": [
                {
                    "name": "caching",
                    "options": {
                        "behavior": "MAX_AGE",
                        "mustRevalidate": false,
                        "ttl": "1d"
                    }
                },
                {
                    "name": "cacheKeyQueryParams",
                    "options": {
                        "behavior": "INCLUDE_ALL_ALPHABETIZE_ORDER"
                    }
                }
            ],
            "children": children,
            "criteriaMustSatisfy": "all",
            "options": { "is_secure": true }
        }
    });

    let config = serde_json::json!({
        "_generated_by": "quant-cache v0.5",
        "_target": "akamai",
        "_ir_summary": {
            "backend": format!("{:?}", ir.backend),
            "capacity_bytes": ir.capacity_bytes,
        },
        "rule_tree": rule_tree,
        "edgeworker_bundle": edgeworker,
        "prewarm_urls": ir.prewarm_set,
        "_deploy_steps": [
            "1. Create new property version via PAPI: POST /papi/v1/properties/{propertyId}/versions",
            "2. PUT rule tree to /papi/v1/properties/{propertyId}/versions/{version}/rules",
            "3. If edgeworker_bundle is present: create EW via EdgeWorkers API, replace {{QC_EDGEWORKER_ID}}",
            "4. Activate version: POST /papi/v1/activations (requires EdgeGrid auth)",
            "5. Warm prewarm_urls via Akamai Fast Purge API or direct requests",
        ]
    });

    let json = serde_json::to_string_pretty(&config)?;
    std::fs::write(output, &json)?;

    let stdout = std::io::stdout();
    let mut out = stdout.lock();
    writeln!(out, "Compiled PolicyIR → Akamai Property Manager rule tree")?;
    writeln!(out, "  Child rules: {}", children.len())?;
    writeln!(out, "  Prewarm URLs: {}", ir.prewarm_set.len())?;
    writeln!(
        out,
        "  EdgeWorker: {}",
        if edgeworker.is_some() {
            "yes (admission gate)"
        } else {
            "no"
        }
    )?;
    if score_map.is_some() {
        writeln!(out, "  Scores: populated from optimize output")?;
    }
    writeln!(out, "  Output → {}", output.display())?;
    Ok(())
}

pub(super) fn compile_akamai_bypass(rule: &BypassRule, children: &mut Vec<serde_json::Value>) {
    match rule {
        BypassRule::None => {}
        BypassRule::SizeLimit { max_bytes } => {
            // Akamai PAPI has no native response-size criterion.
            // Emit as advisory-only (not an active rule) to avoid disabling
            // cache for all traffic. Size-based bypass requires an EdgeWorker
            // that checks Content-Length and sets a bypass header.
            children.push(serde_json::json!({
                "name": format!("qc: bypass objects > {} bytes (ADVISORY)", max_bytes),
                "criteria": [{
                    "name": "requestHeader",
                    "options": {
                        "headerName": "X-QC-Size-Bypass",
                        "matchOperator": "IS_ONE_OF",
                        "values": ["true"],
                        "matchWildcardName": false,
                        "matchCaseSensitiveValue": false
                    }
                }],
                "behaviors": [
                    {
                        "name": "caching",
                        "options": { "behavior": "NO_STORE" }
                    }
                ],
                "children": [],
                "criteriaMustSatisfy": "all",
                "_note": format!(
                    "Akamai PAPI has no native content-length criterion. \
                     Deploy an EdgeWorker that sets X-QC-Size-Bypass: true \
                     for responses > {} bytes, then this rule activates.",
                    max_bytes
                )
            }));
        }
        BypassRule::FreshnessRisk { .. } => {
            children.push(serde_json::json!({
                "name": "qc: bypass high-churn API content",
                "criteria": [{
                    "name": "contentType",
                    "options": {
                        "matchOperator": "IS_ONE_OF",
                        "matchWildcard": false,
                        "matchCaseSensitive": false,
                        "values": ["application/json"]
                    }
                }],
                "behaviors": [
                    { "name": "caching", "options": { "behavior": "NO_STORE" } },
                    { "name": "downstreamCache", "options": { "behavior": "BUST" } }
                ],
                "children": [],
                "criteriaMustSatisfy": "all"
            }));
        }
        BypassRule::Any { rules } => {
            for r in rules {
                compile_akamai_bypass(r, children);
            }
        }
    }
}

pub(super) fn seconds_to_akamai_ttl(s: u64) -> String {
    if s >= 86400 && s % 86400 == 0 {
        format!("{}d", s / 86400)
    } else if s >= 3600 && s % 3600 == 0 {
        format!("{}h", s / 3600)
    } else if s >= 60 && s % 60 == 0 {
        format!("{}m", s / 60)
    } else {
        format!("{}s", s)
    }
}

pub(super) fn gen_akamai_edgeworker(
    threshold: f64,
    mode: &str,
    score_map: Option<&HashMap<String, f64>>,
    cache_key_config: Option<&serde_json::Value>,
) -> String {
    let scores_js = if let Some(map) = score_map {
        // Use JSON serialization to safely escape keys (prevents JS injection)
        let safe_map: HashMap<&str, f64> = map
            .iter()
            .filter(|(_, &v)| v > threshold)
            .map(|(k, &v)| (k.as_str(), (v * 10000.0).round() / 10000.0))
            .collect();
        serde_json::to_string_pretty(&safe_map).unwrap_or_else(|_| "{}".into())
    } else {
        "{ /* Run: qc compile --scores policy.json to populate */ }".to_string()
    };

    let strip_params = cache_key_config
        .and_then(|cfg| cfg["query_string_strip"].as_array())
        .map(|params| {
            params
                .iter()
                .filter_map(|p| p.as_str())
                .map(|p| format!("'{p}'"))
                .collect::<Vec<_>>()
                .join(", ")
        })
        .unwrap_or_default();

    format!(
        r#"// quant-cache admission gate EdgeWorker
// Mode: {mode}, threshold: {threshold}

const SCORES = {scores_js};
const STRIP_PARAMS = [{strip_params}];

function shouldStripParam(name) {{
  for (let i = 0; i < STRIP_PARAMS.length; i++) {{
    const pattern = STRIP_PARAMS[i];
    if (pattern.endsWith('*')) {{
      if (name.startsWith(pattern.slice(0, -1))) return true;
    }} else if (name === pattern) {{
      return true;
    }}
  }}
  return false;
}}

function normalizedKey(request) {{
  const params = [];
  if (request.query) {{
    const sorted = request.query.split('&').map(p => p.split('=')[0]).sort();
    const queryMap = {{}};
    for (const pair of request.query.split('&')) {{
      const idx = pair.indexOf('=');
      if (idx >= 0) queryMap[pair.slice(0, idx)] = pair.slice(idx + 1);
    }}
    for (const name of sorted) {{
      if (shouldStripParam(name)) continue;
      params.push(name + '=' + (queryMap[name] || ''));
    }}
  }}
  return params.length ? request.path + '?' + params.join('&') : request.path;
}}

export function onClientRequest(request) {{
  const key = normalizedKey(request);
  const score = SCORES[key];
  if (score === undefined || score <= {threshold}) {{
    // Sub-threshold: bypass cache
    request.setHeader('X-QC-Bypass', 'true');
    request.route({{ origin: 'default', cacheKey: null }});
  }}
}}
"#
    )
}

pub(super) fn extract_strip_params(
    cache_key_rules: &[qc_model::policy_ir::CacheKeyRule],
) -> Vec<&str> {
    let mut params = Vec::new();
    for r in cache_key_rules {
        if r.pattern.contains("utm_") {
            params.extend([
                "utm_source",
                "utm_medium",
                "utm_campaign",
                "utm_content",
                "utm_term",
            ]);
        }
        if r.pattern.contains("fbclid") {
            params.push("fbclid");
        }
    }
    params.sort();
    params.dedup();
    params
}

pub(super) fn validate_akamai(config: &serde_json::Value) -> Vec<String> {
    let mut issues = Vec::new();

    if config["_target"] != "akamai" {
        issues.push("_target should be 'akamai'".into());
    }

    let rule_tree = &config["rule_tree"];
    if rule_tree.is_null() {
        issues.push("missing 'rule_tree' in output".into());
        return issues;
    }

    let root = &rule_tree["rules"];
    if root.is_null() {
        issues.push("missing 'rule_tree.rules' root".into());
        return issues;
    }

    if root["name"] != "default" {
        issues.push(format!(
            "root rule name should be 'default', got {:?}",
            root["name"]
        ));
    }

    if let Some(children) = root["children"].as_array() {
        for (i, child) in children.iter().enumerate() {
            let ctx = format!("children[{i}]");

            if child["name"].as_str().unwrap_or("").is_empty() {
                issues.push(format!("{ctx}: missing 'name'"));
            }

            if let Some(behaviors) = child["behaviors"].as_array() {
                for (j, behavior) in behaviors.iter().enumerate() {
                    if behavior["name"].as_str().unwrap_or("").is_empty() {
                        issues.push(format!("{ctx}.behaviors[{j}]: missing behavior 'name'"));
                    }
                }
                // Check for unreplaced EdgeWorker placeholder
                for b in behaviors {
                    if b["name"] == "edgeWorker" {
                        if let Some(ew_id) = b["options"]["edgeWorkerId"].as_str() {
                            if ew_id.contains("{{") {
                                issues.push(format!(
                                    "{ctx}: edgeWorkerId contains unreplaced placeholder '{ew_id}'"
                                ));
                            }
                        }
                    }
                }
            } else {
                issues.push(format!("{ctx}: missing 'behaviors' array"));
            }
        }

        if children.len() > 100 {
            issues.push(format!(
                "too many child rules: {} (recommended max: 100)",
                children.len()
            ));
        }
    }

    // Validate EdgeWorker bundle
    if let Some(bundle) = config["edgeworker_bundle"].as_str() {
        if bundle.contains("/* Run: qc compile --scores") || bundle.contains("/* populate") {
            issues.push("EdgeWorker bundle contains unpopulated placeholder scores".into());
        }
        if bundle.len() > 1_000_000 {
            issues.push(format!(
                "EdgeWorker bundle exceeds 1MB ({} bytes)",
                bundle.len()
            ));
        }
    }

    if let Some(urls) = config["prewarm_urls"].as_array() {
        for (i, url) in urls.iter().enumerate() {
            if let Some(u) = url.as_str() {
                if !u.starts_with('/') {
                    issues.push(format!("prewarm_urls[{i}]: should start with '/'"));
                }
            }
        }
    }

    issues
}
